
# This file describes the alternative machine learning models
# available to InvokeAI script.
#
# To add a new model, follow the examples below. Each
# model requires a model config file, a weights file,
# and the width and height of the images it
# was trained on.
stable-diffusion-1.5:
  description: Stable Diffusion version 1.5 diffusers model (4.27 GB)
  repo_id: runwayml/stable-diffusion-v1-5
  format: diffusers
  vae:
    repo_id: stabilityai/sd-vae-ft-mse
  default: true
sd-inpainting-1.5:
  description: RunwayML SD 1.5 model optimized for inpainting, diffusers version (4.27
    GB)
  repo_id: runwayml/stable-diffusion-inpainting
  format: diffusers
  vae:
    repo_id: stabilityai/sd-vae-ft-mse
stable-diffusion-2.1-768:
  description: Stable Diffusion version 2.1 diffusers model, trained on 768 pixel
    images (5.21 GB)
  repo_id: stabilityai/stable-diffusion-2-1
  format: diffusers
